---
- name: Project scafolding lecture 22 and 23
  hosts: localhost
  gather_facts: no
  vars:
    - base_dir: ~/Docker/Projects/MobyDock/mobydock
  tasks:
    - name: Create all the directories
      file: path={{ base_dir }}/{{ item }} state=directory
      with_items:
        - mobydock
        - config
        - instance
        - mobydock/templates
        - mobydock/static


    - name: Create the files in mobydock
      file: path={{ base_dir }}/{{ item }} state=touch
      with_items:
        - requirements.txt
        - .gitignore
        - Dockerfile
        - docker-compose.yml
        - .dockerignore

    - name: Create files in directories inside mobydock
      file: path={{ base_dir }}/{{ item }} state=touch
      with_items:
        - config/__init__.py
        - config/setting.py
        - instance/__init__.py
        - instance/settings.py_production_example
        - mobydock/app.py
        - mobydock/__init__.py
        - mobydock/templates/layout.html
        - mobydock/static/main.css

    - name: Download the Docker image
      get_url:
        url: http://doc.rultor.com/images/docker-logo.png
        dest: "{{ base_dir }}/mobydock/static/docker-logo.png"
