---
- name: Project scafolding lecture 23
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: Create all the directories
      file: path=~/Docker/Projects/{{ item }} state=directory mode=0644
      with_items:
        - MobyDock/mobydock/mobydock
        - MobyDock/mobydock/config
        - MobyDock/mobydock/instance
        - MobyDock/mobydock/mobydock/template
        - MobyDock/mobydock/mobydock/static

    - name: Create the files in mobydock
      file: path=~/Projects/MobyDock/mobydock/{{ item }} state=touch
      with_items:
        - requirements.txt
        - .gitignore
        - Dockerfile
        - docker-compose.yml
        - .dockerignore

    - name: Create files in directories inside mobydock
      file: path=~/Projects/MobyDock/mobydock/{{ item }} state=touch
      with_items:
        - config/__init__.py
        - config/setting.py
        - instance/__init__.py
        - instance/settings.py_production_example
        - mobydock/app.py
        - mobydock/__init__.py
        - templates/layout.html
        - static/main.css

    - name: Download the Docker image
      get_url:
        url: http://doc.rultor.com/images/docker-logo.png
        dest: ~/Projects/MobyDock/mobydock/static/docker-logo.png
